# Periliminal.Space — futuristic neon downtown style for OSM2World.
# Copied next to OSM2World's standard.properties at bake time so relative
# texture paths resolve. The bake script defaults to standard.properties
# for conversion reliability; the Blender align pass applies the neon look.

include = ./standard.properties

createTerrain = false
useBuildingColors = true
useBillboards = false
renderUnderground = false
treesPerSquareMeter = 0.005

material_BUILDING_DEFAULT_color = #a8c4d8
material_GLASS_color = #6ec8ff
material_CONCRETE_color = #5a6570
material_STEEL_color = #8a9aaa
material_ROOF_DEFAULT_color = #2a3340
material_ASPHALT_color = #1a1c20
material_ROAD_MARKING_color = #c8e6ff
