## Autoload (registered in project.godot). Do NOT add class_name.
## Autoload. Manages LingBot-World generated reference assets.
##
## Pipeline:
##   1. Run Google Colab notebook (scripts/LingBot_World_Colab_Pipeline.ipynb)
##   2. Download zip → extract to assets/references/lingbot/
##   3. This module loads videos/textures for in-engine reference display
##   4. Visual prompts feed into loading screens, skyboxes, and environment previews

extends Node

## Environment IDs matching the Colab generation notebook
const ENVIRONMENTS := {
	"subliminal": {
		"name": "Subliminal — Home",
		"prompt": "A warm cat-themed apartment with purple neon ambient lighting",
		"frames": 81,
	},
	"liminal": {
		"name": "Liminal — The Between",
		"prompt": "Endless void with Victorian hallways, floating doors, indigo fog",
		"frames": 81,
	},
	"hyperliminal": {
		"name": "Hyperliminal — Catsino",
		"prompt": "Cat-themed casino with golden paw chandeliers, art deco, red velvet",
		"frames": 81,
	},
	"periliminal": {
		"name": "Periliminal — The Anchor",
		"prompt": "Surreal psychological landscape, floating platforms, broken mirrors",
		"frames": 81,
	},
	"extraliminal": {
		"name": "Extraliminal — The Overlay",
		"prompt": "Holographic AR layer over DFW, cyan data streams, digital fireflies",
		"frames": 81,
	},
	"dallas": {
		"name": "New Dallas",
		"prompt": "Futuristic Dallas skyline at golden hour, neon Reunion Tower",
		"frames": 121,
	},
	"fort_worth": {
		"name": "Hell's Half Acre",
		"prompt": "Cyberpunk Western hybrid, neon cattle skulls, dust storms",
		"frames": 121,
	},
	"denton": {
		"name": "Sky Fjord",
		"prompt": "Floating college town built into a cliff face, waterfalls, glass domes",
		"frames": 121,
	},
	"arlington": {
		"name": "Soulless Sanctuary",
		"prompt": "Arena city with spherical stadium, space elevator, gladiator pit",
		"frames": 121,
	},
	"supraliminal_overview": {
		"name": "DFW Metroplex",
		"prompt": "Sprawling futuristic metroplex, four cores, maglev trains",
		"frames": 81,
	},
}

## Reference video presence flags (loaded from assets/references/lingbot/)
var _video_present: Dictionary = {}  # env_id -> bool
var _loaded := false


func _ready() -> void:
	_load_reference_assets()


## Scan for reference video files on disk. Videos are MP4 files generated by
## the Colab pipeline. Godot 4.7 does not play MP4 natively — these are
## tracked as file paths for external reference (visual direction, skybox
## authoring, loading screen thumbnails).
func _load_reference_assets() -> void:
	var ref_dir: String = "res://assets/references/lingbot/videos/"
	var dir: DirAccess = DirAccess.open(ref_dir)
	if dir == null:
		push_warning("LingBotIntegration: No reference videos found at %s (run Colab pipeline first)" % ref_dir)
		_load_prompts_only()
		return

	var count := 0
	for env_id in ENVIRONMENTS.keys():
		var path: String = ref_dir.path_join(env_id + ".mp4")
		if ResourceLoader.exists(path):
			_video_present[env_id] = true
			count += 1

	_loaded = true
	print("[LingBotIntegration] Found %d/%d reference videos (MP4)" % [count, ENVIRONMENTS.size()])


## Load just the prompt text (no video assets needed).
func _load_prompts_only() -> void:
	_loaded = true
	print("[LingBotIntegration] Running in prompt-only mode (%d environments)" % ENVIRONMENTS.size())


## Returns true if reference assets are loaded.
func has_references() -> bool:
	return _loaded


## Returns true if a reference video file exists for this environment.
func has_video(env_id: String) -> bool:
	return _video_present.get(env_id, false)


## Get the environment's generation prompt (used for visual direction).
func get_prompt(env_id: String) -> String:
	var env: Dictionary = ENVIRONMENTS.get(env_id, {})
	return env.get("prompt", "")


## Get the environment's display name.
func get_env_name(env_id: String) -> String:
	var env: Dictionary = ENVIRONMENTS.get(env_id, {})
	return env.get("name", env_id)


## Get all available environment IDs.
func get_environment_ids() -> Array[String]:
	return ENVIRONMENTS.keys().duplicate()


## Get the file path for a reference video, or empty string if not found.
## Videos are MP4 files generated by the Colab pipeline for visual reference.
## Godot 4.7 does not play MP4 natively — these are for external review.
func get_video_path(env_id: String) -> String:
	var path: String = "res://assets/references/lingbot/videos/" + env_id + ".mp4"
	if ResourceLoader.exists(path):
		return path
	return ""


## Create a preview card (Control) showing the reference for a given environment.
## Useful for loading screens, environment selectors, etc.
func create_preview_card(env_id: String) -> Control:
	var container: MarginContainer = MarginContainer.new()
	container.add_theme_constant_override("margin_left", 8)
	container.add_theme_constant_override("margin_right", 8)
	container.add_theme_constant_override("margin_top", 8)
	container.add_theme_constant_override("margin_bottom", 8)

	var vbox: VBoxContainer = VBoxContainer.new()
	container.add_child(vbox)

	# Environment name
	var title: Label = Label.new()
	title.text = get_env_name(env_id)
	title.add_theme_font_size_override("font_size", 18)
	title.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	vbox.add_child(title)

	# Reference info — videos are MP4 external files (Godot doesn't play MP4)
	var info_text: String = get_prompt(env_id)
	if has_video(env_id):
		info_text += "\n\n[📁 Reference video available — open in external player]"

	var placeholder: Label = Label.new()
	placeholder.text = info_text
	placeholder.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	placeholder.custom_minimum_size = Vector2(320, 180)
	placeholder.add_theme_color_override("font_color", Color(0.6, 0.6, 0.8))
	placeholder.add_theme_font_size_override("font_size", 12)
	vbox.add_child(placeholder)

	# Frame count info
	var info: Label = Label.new()
	var env: Dictionary = ENVIRONMENTS.get(env_id, {})
	info.text = "%d frames" % env.get("frames", 0)
	info.add_theme_font_size_override("font_size", 11)
	info.add_theme_color_override("font_color", Color(0.5, 0.5, 0.6))
	info.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	vbox.add_child(info)

	return container
